baseURL = "https://wangxiaohong123.github.io/" # 替换为你的 GitHub Pages 地址
languageCode = "zh-CN"
title = "王小红的笔记"
theme = "PaperMod"

[params]
  homeInfoParams.Title = "Flutter 技术笔记"
  homeInfoParams.Content = "记录 Flutter 高级使用与实践"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  copyright = "© 2025 why. All rights reserved."
  enableInlineShortcodes = true
  enableMath = true
  disableGoogleAnalytics = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "dracula" # 适配 Flutter/Dart 代码高亮
    lineNos = true    # 显示代码行号

[[menu.main]]
  identifier = "posts"
  name = "笔记"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 30

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 20
